apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cbb
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - redis.yaml
  - next-app.yaml
  - api-server.yaml
  - ai-service.yaml
  - media-server.yaml
  - ingress.yaml
